//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.20 at 03:04:10 PM EEST 
//


package lt.viko.eif.rcepauskas.soap;

import lt.viko.eif.rcepauskas.blog.User;
import lt.viko.eif.rcepauskas.blog.Post;
import lt.viko.eif.rcepauskas.soap.methods.post.*;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost.web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost.web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPostRequest }
     * 
     */
    public GetPostRequest createGetPostRequest() {
        return new GetPostRequest();
    }

    /**
     * Create an instance of {@link GetPostResponse }
     * 
     */
    public GetPostResponse createGetPostResponse() {
        return new GetPostResponse();
    }

    /**
     * Create an instance of {@link Post }
     * 
     */
    public Post createPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link GetPostsRequest }
     * 
     */
    public GetPostsRequest createGetPostsRequest() {
        return new GetPostsRequest();
    }

    /**
     * Create an instance of {@link GetPostsResponse }
     * 
     */
    public GetPostsResponse createGetPostsResponse() {
        return new GetPostsResponse();
    }

    /**
     * Create an instance of {@link InsertPostRequest }
     * 
     */
    public InsertPostRequest createInsertPostRequest() {
        return new InsertPostRequest();
    }

    /**
     * Create an instance of {@link InsertPostResponse }
     * 
     */
    public InsertPostResponse createInsertPostResponse() {
        return new InsertPostResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdatePostRequest }
     * 
     */
    public UpdatePostRequest createUpdatePostRequest() {
        return new UpdatePostRequest();
    }

    /**
     * Create an instance of {@link UpdatePostResponse }
     * 
     */
    public UpdatePostResponse createUpdatePostResponse() {
        return new UpdatePostResponse();
    }

    /**
     * Create an instance of {@link DeletePostRequest }
     * 
     */
    public DeletePostRequest createDeletePostRequest() {
        return new DeletePostRequest();
    }

    /**
     * Create an instance of {@link DeletePostResponse }
     * 
     */
    public DeletePostResponse createDeletePostResponse() {
        return new DeletePostResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
